application: nathan-lam
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon1\.ico
  static_files: favicon1.ico
  upload: favicon1\.ico

- url: /css
  static_dir: css

- url: /Font-Awesome-master
  static_dir: Font-Awesome-master

- url: /Hover-master
  static_dir: Hover-master

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: .*
  script: main.php
